<?php // module/Admin/view/layout/admin.phtml  ?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8"></meta>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/bootstrap/2.3.2/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/bootstrap/2.3.2/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/themes/admin/default/1.0/css/style.css')
                ?>

        <!-- Scripts -->
        <script type='text/javascript' src="/assets/jquery/1.9.1/jquery.min.js"></script>
        <script type='text/javascript' src="/assets/bootstrap/2.3.2/js/bootstrap.min.js"></script>
        <script type='text/javascript' src="/assets/highcharts/3.0.0/highcharts.js"></script>
        
        <?php /* echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                          ->prependFile($this->basePath() . '/assets/bootstrap/2.3.2/js/bootstrap.min.js','text/javascript')
                          ->prependFile($this->basePath() . '/assets/jquery/1.9.1/jquery.min.js','text/javascript') 
                          ->prependFile($this->basePath() . '/assets/jquery/jquery-migrate-1.1.1.min.js','text/javascript') 
                          ->prependFile($this->basePath() . '/assets/highcharts/3.0.0/highcharts.js','text/javascript'); */ ?>        
        
    </head>

    <body>
        
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="#"><?php echo $this->translate('Admin'); ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#contact">Contact</a></li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->translate('Dropdown') ?></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a tabindex="-1" href="#"><?php echo $this->translate('Action'); ?></a></li>      
                                    <li><a tabindex="-1" href="#"><?php echo $this->translate('Another action'); ?></a></li>
                                    <li><a tabindex="-1" href="#"><?php echo $this->translate('Something else here'); ?></a></li>
                                    <li class="divider"></li>
                                    <li><a tabindex="-1" href="#">Separated link</a></li>
                                </ul>                              
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        
        <div class="container-fluid">
            <?php echo $content; ?>            
        </div>
    
    <?php echo $this->inlineScript()->prependFile($this->basePath() . '/themes/admin/default/1.0/js/charts.js') ?>
    </body>
</html>



