<?php
// module/Backoffice/view/backoffice/user/add.phtml:
// http://stackoverflow.com/questions/15125020/zend-framework-2-output-form-element-objects-as-html-fields

$title = 'Backoffice / User::add';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
/*
if( $this->form) {
    echo $this->form()->openTag($this->form);
    echo $this->formCollection($this->form);
    echo $this->form()->closeTag($this->form); 
} */
?>

<?php
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="element element_name">
    <?php echo $this->formRow($form->get('username')); ?>
</div>

<div class="element element_name">
    <?php echo $this->formRow($form->get('email')); ?>
</div>

<div class="element element_submit">
    <?php echo $this->formRow($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>


<pre><?php print_r($this->form); ?></pre>