<?php
// module/Backoffice/view/backoffice/user/index.phtml:

$title = 'Backoffice / User::index';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?print_r($this->username);?>

<p>
    <a href="<?php echo $this->url('user', array('action'=>'add'));?>"><?php echo $this->translate("Add new user"); ?></a>
</p>

<table class="table table-striped">
<tr>
    <th><?php echo $this->translate("ID"); ?></th>
    <th><?php echo $this->translate("Username"); ?></th>
    <th><?php echo $this->translate("Email"); ?></th>
    <th><?php echo $this->translate("Date"); ?></th>
    <th><?php echo $this->translate("Status"); ?></th>    
    <th><?php echo $this->translate("Action"); ?></th>
    <th style="width: 100px;"> </th>
</tr>
<?php foreach ($this->paginator as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->id);?></td>
    <td><a href="<?php echo $this->url('user', array('action'=>'view', 'id' => $user->id));?>"><?php echo $this->escapeHtml($user->username);?></a></td>
    <td><?php echo $this->escapeHtml($user->email);?></td>
    <td><?php echo $this->escapeHtml($user->date);?></td>
    <td><?php echo $this->escapeHtml($user->status);?></td>
    <td>
        <a href="<?php echo $this->url('user', array('action'=>'edit', 'id' => $user->id));?>"><?php echo $this->translate("Edit"); ?></a>
        <a href="<?php echo $this->url('user', array('action'=>'delete', 'id' => $user->id));?>"><?php echo $this->translate("Delete"); ?></a>
    </td>
    <td>
        <div class="btn-group pull-right">
            <button class="btn btn-small dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate("Action"); ?> <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('user', array('action'=>'edit', 'id' => $user->id));?>"><?php echo $this->translate("Edit"); ?></a></li>
                <li><a href="<?php echo $this->url('user', array('action'=>'delete', 'id' => $user->id));?>"><?php echo $this->translate("Delete"); ?></a></li>
            </ul>
        </div>        
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'Backoffice'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'user'
    )
);
?>
