<?php
// module/Admin/view/admin/system/add.phtml:
$title = 'System Add';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php /*
<div class="container">
<form id="step" class="form-horisontal">
  <fieldset title="Step 1">
    <legend>Owner details</legend>
    <!-- inputs -->
    <div class="form-group">
		<label for="exampleInputUsername">Username</label>
		<input type="text" class="form-control" id="exampleInputEmail" placeholder="Username">
	</div>    
    <div class="form-group">
		<label for="exampleInputEmail">Email address</label>
		<input type="text" class="form-control" id="exampleInputEmail" placeholder="Enter email">
	</div>
    <div class="form-group">
      <label for="exampleInputPassword">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword" placeholder="Password">
    </div>	
  </fieldset>

  <fieldset title="Step 2">
    <legend>System details</legend>
    <!-- inputs -->
     <div class="form-group">
		<label for="exampleInputEmail">First Name</label>
		<input type="text" class="form-control" id="exampleInputEmail" placeholder="Enter email">
	</div>   
  </fieldset>

  <fieldset title="Step 3">
    <legend>Database</legend>
  </fieldset>

  <fieldset title="Step 4">
    <legend>Description four</legend>
  </fieldset>
  <input type="submit" class="btn btn-success finish" />
</form> 
</div> */ ?>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/system', array('action' => 'add')));
$form->prepare(); ?>



<div class="container">
<?php echo $this->form()->openTag($form); ?>

<div class="form-group">
<?php echo $this->formHidden($form->get('id')); ?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('name')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>

<?php echo $this->form()->closeTag(); ?>
</div>


<?php print_r($this->form->getMessages() ); ?>