<?php
// module/Admin/view/admin/system/view.phtml:
$title = 'System View: ' . $system->getName();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php print_r($system->getName() ); ?>


<?php 
    $users = $system->getUsers();
    foreach($users as $user):  ?>
        <p><b><?php echo $user->getUsername()?></b>, <?php echo $user->getEmail()?></p>
<?php endforeach;
?>


<h2>System objects</h2>

<h3>Users</h3>
<ul>
    <li>Owner</li>
    <li>Managers</li>
    <li>Affiliates</li>
</ul>

<h3>Sites</h3>

<h3>Campaigns</h3>

<h3>Campaigns / Rates</h3>
