<?php
// module/Backoffice/view/backoffice/auth/login.phtml:

$title = 'Please sign in';
$this->headTitle($title);
?>



<?php
if ($this->loginSuccess) {
    echo "Hello, " . $this->userLoggedIn . '!';
}
else {
    if ($this->loginError) {
        echo "The credentials provided are invalid.";
    }
}

    $this->form->prepare(); ?>

<?php echo $this->form()->openTag($this->form); ?>

<h2 class="form-signin-heading"><?php echo $this->escapeHtml($title); ?></h2>
    
<div class="control-group">
    <label class="control-label" for="username">Username</label>
    <div class="controls"><?php echo $this->formRow($this->form->get('username'));?></div>
</div>
    
<div class="control-group">
    <label class="control-label" for="password">Password</label>
    <div class="controls"><?php echo $this->formRow($this->form->get('password'));?></div>
</div>    
    
<div class="control-group">
    <div class="controls"><?php echo $this->formSubmit($this->form->get('submit')); ?></div>
</div>
    
<?php echo $this->form()->closeTag(); ?>
