<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Backoffice'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('backoffice') ?>"><?php echo $this->translate('BackOffice') ?><sup>™</sup></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-left">
                            <li class="active"><a href="<?php echo $this->url('backoffice') ?>"><?php echo $this->translate('Dashboard') ?></a></li>
                            <li class=""><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('User') ?></a></li>
                            <li class=""><a href="<?php echo $this->url('site') ?>"><?php echo $this->translate('Site') ?></a></li>
                            <li class=""><a href="#"><?php echo $this->translate('Campaign') ?></a></li>
                            <li class=""><a href="#"><?php echo $this->translate('Rate') ?></a></li>
                            <li class=""><a href="#"><?php echo $this->translate('Payment') ?></a></li>
                            
                        </ul>
                        
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->translate('My Account') ?></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a tabindex="-1" href="#"><?php echo $this->translate('Profile'); ?></a></li>      
                                    <li><a tabindex="-1" href="#"><?php echo $this->translate('Action'); ?></a></li>
                                    <li><a tabindex="-1" href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logout'); ?></a></li>
                                </ul>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container-fluid" style="min-height: 800px;">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        
        <footer>
            <p>&copy; 2005 - 2012 by Vasil Dakov. <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
