<?php
// module/Blog/view/blog/blog/index.phtml:

$title = $this->translate('Blog Module');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
  <a href="<?php echo $this->url('post', array('action'=>'add'));?>">Add new Post</a>
</p>
<?php foreach ($posts as $post) : ?>
<article>
  <h1><?php echo $this->escapeHtml($post->getTitle());?></h1>
  <p>
    <?php echo $this->escapeHtml($post->getText());?>
  </p>
  <aside>
    <ul>
      <li><a href="<?php echo $this->url('post', array(
        'action'=>'edit',
        'id'=>$post->getId()
      ));
      ?>">Edit this Post</a></li>
      <li><a href="<?php echo $this->url('post', array(
        'action'=>'delete',
        'id'=>$post->getId()
      ));?>">Delete this Post</a></li>
    </ul>
  </aside>
</article>
<?php endforeach; ?>