<h1>Admin Theme Design</h1>
<?php
/**
 * Inspired Design
 * http://themes.flatfull.com/first/v.3.0/landing.html
 * http://themes.flatfull.com/first/v.3.0/form.html
 */
?>

<!-- tabbable -->
<div class="tabbable">
    
    <!-- nav tabs -->
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#typography"><?php echo $this->translate("Typography"); ?></a></li>
        <li><a data-toggle="tab" href="#elements"><?php echo $this->translate("Elements"); ?></a></li>
        <li><a data-toggle="tab" href="#lists"><?php echo $this->translate("Lists"); ?></a></li>
        <li><a data-toggle="tab" href="#forms"><?php echo $this->translate("Forms"); ?></a></li>
        <li><a data-toggle="tab" href="#charts"><?php echo $this->translate("Charts"); ?></a></li>
        <li><a data-toggle="tab" href="#bar"><?php echo $this->translate("Bar"); ?></a></li>
        <li><a data-toggle="tab" href="#foo"><?php echo $this->translate("Foo"); ?></a></li>
    </ul>
    
    <!-- tab content -->
    <div class="tab-content">
        <div id="typography" class="tab-pane active">
            <p>Typography</p>
        </div>
        
        <div id="elements" class="tab-pane">
            <ul>
                <li>Buttons</li>
                <li>Icons</li>
            </ul>
        </div>
        
        <div id="lists" class="tab-pane"><p>Lists</p></div>
        
        <div id="forms" class="tab-pane"><p>Forms</p></div>
        
        <div id="charts" class="tab-pane">
            <div id="container" style="width: 100%; overflow:hidden; height: 400px; margin: 0 auto"></div>
        </div>
        
        <div id="bar" class="tab-pane"><p>I'm in Section 1.</p></div>
        
        <div id="foo" class="tab-pane"><p>Howdy, I'm in Section 2.</p></div>
    </div>
</div>

