<h1>Dashboard</h1>
<?php print_r($this->message);?>

<?php /*
<div class="container">
  <?php $form = $this->form; ?>
  <?php $form->prepare(); ?>
  <?php echo $this->form()->openTag($form); ?>
  <?php echo $this->formRow($form->get('username')); ?>
  <?php echo $this->formSubmit($form->get('submit')); ?>
  <?php echo $this->form()->closeTag(); ?>
</div> */ ?>

<?php echo $this->TestHelper("me","e"); ?>

<div class="" style="padding: 10px;">
    <div class="row">
        <div class=".col-12 col-lg-6">
            <div class="list-group">
              <a href="#" class="list-group-item active">Cras justo odio</a>
              <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
              <a href="#" class="list-group-item">Morbi leo risus</a>
              <a href="#" class="list-group-item">Porta ac consectetur ac</a>
              <a href="#" class="list-group-item">Vestibulum at eros</a>
            </div>
            
            <ul class="list-group">
              <a href="#" class="list-group-item active">List group item heading</a>
              <li class="list-group-item">Cras justo odio <span class="badge">32</span></li>
              <li class="list-group-item">Dapibus ac facilisis in <span class="badge">48</span></li>
              <li class="list-group-item">Morbi leo risus <span class="badge">54</span></li>
              <li class="list-group-item">Porta ac consectetur ac <span class="badge">12</span></li>
              <li class="list-group-item">Vestibulum at eros <span class="badge">26</span></li>
            </ul>
        </div>
        
        <div class=".col-12 col-lg-6">
            <ul class="list-group">
              <li class="list-group-item">
                <span class="badge">14</span>
                Cras justo odio
              </li>
            </ul>
        </div>        
    </div>
    
</div>

<pre><?php print_r(apc_cache_info()); ?></pre>

<h3>Systems</h3>

<h3>Users</h3>

<h3>Sites</h3>

<h3>Campaigns</h3>